const mongoose = require('mongoose')
const { MONGODB_URI } = require('../../config')
mongoose.connect(MONGODB_URI)
  .then(() => console.log('Connected to MongoDB'))
  .catch(err => console.error('Error connecting to database: ', err.message))